import { execSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const root = resolve(here, "..");
const assetsDir = resolve(root, "src/render/assets");
const outPath = resolve(root, "src/render/assets.generated.ts");
const clientTsConfig = resolve(root, "tsconfig.client.json");
const compiledDir = resolve(root, ".tsc-client");
const compiledJs = resolve(compiledDir, "arg-render.js");

// 1. Compile arg-render.ts via the client tsconfig (DOM lib, ES2022).
execSync(`pnpm exec tsc -p ${JSON.stringify(clientTsConfig)}`, {
  stdio: "inherit",
  cwd: root,
});

// 2. Read the compiled JS and strip ESM `export` keywords so the script runs
//    as a plain <script> in the browser. The renderer only exports top-level
//    declarations; stripping the keyword leaves valid script-mode JS.
const compiled = readFileSync(compiledJs, "utf8");
const stripped = compiled
  .replace(/^export\s+(function|const|let|var|class)\s+/gm, "$1 ")
  .replace(/^export\s+\{[^}]*\};?\s*$/gm, "");

// 3. Wrap in an IIFE that invokes mount() against the live document.
const bundled = `(function () {\n${stripped}\nmount(document, window);\n})();\n`;

// 4. Bake CSS + bundled JS into assets.generated.ts.
const css = readFileSync(resolve(assetsDir, "arg-render.css"), "utf8");

const banner = [
  "// @generated by scripts/generate-render-assets.ts",
  "// Do not edit by hand. Run `pnpm generate-render-assets` to refresh.",
  "// Source: src/render/assets/arg-render.{css,ts}",
  "",
].join("\n");

const body = [
  `export const ARG_RENDER_CSS: string = ${JSON.stringify(css)};`,
  "",
  `export const ARG_RENDER_JS: string = ${JSON.stringify(bundled)};`,
  "",
].join("\n");

writeFileSync(outPath, banner + body, "utf8");

// 5. Clean up the tsc output directory.
rmSync(compiledDir, { recursive: true, force: true });

process.stdout.write(
  `generate-render-assets: wrote ${outPath} (css ${css.length}B, js ${bundled.length}B)\n`,
);
