// Bundles the client-side renderer (`src/render/assets/arg-render.bootstrap.ts`)
// plus its imports into a single browser-targeted IIFE, then bakes it
// alongside the CSS into `src/render/assets.generated.ts` so `renderHTML`
// can inline both. Type-checking is delegated to `tsconfig.client.json`
// (browser-only, DOM lib, no Node types).

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = fileURLToPath(new URL(".", import.meta.url));
const root = resolve(here, "..");
const assetsDir = resolve(root, "src/render/assets");
const outPath = resolve(root, "src/render/assets.generated.ts");
const clientTsConfig = resolve(root, "tsconfig.client.json");
const entry = resolve(assetsDir, "arg-render.bootstrap.ts");

// 1. Type-check the client bundle against a browser-only tsconfig. This is
//    the gate that ensures arg-render.ts and its imports don't drift into
//    Node-only APIs.
execSync(`pnpm exec tsc -p ${JSON.stringify(clientTsConfig)}`, {
  stdio: "inherit",
  cwd: root,
});

// 2. Bundle with esbuild. IIFE format = self-contained script for inline use.
const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  write: false,
  minify: false,
  treeShaking: true,
  legalComments: "none",
  logLevel: "warning",
});

const [output] = result.outputFiles;
if (!output) throw new Error("generate-render-assets: esbuild produced no output");
const bundled = output.text;

// 3. Bake CSS + bundled JS into assets.generated.ts.
const css = readFileSync(resolve(assetsDir, "arg-render.css"), "utf8");

const banner = [
  "// @generated by scripts/generate-render-assets.ts",
  "// Do not edit by hand. Run `pnpm generate-render-assets` to refresh.",
  "// Source: src/render/assets/arg-render.{css,bootstrap.ts,ts}",
  "",
].join("\n");

const body = [
  `export const ARG_RENDER_CSS: string = ${JSON.stringify(css)};`,
  "",
  `export const ARG_RENDER_JS: string = ${JSON.stringify(bundled)};`,
  "",
].join("\n");

writeFileSync(outPath, banner + body, "utf8");

process.stdout.write(
  `generate-render-assets: wrote ${outPath} (css ${css.length}B, js ${bundled.length}B)\n`,
);
