import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const root = resolve(here, "..");
const assetsDir = resolve(root, "src/render/assets");
const outPath = resolve(root, "src/render/assets.generated.ts");

const css = readFileSync(resolve(assetsDir, "arg-render.css"), "utf8");
const js = readFileSync(resolve(assetsDir, "arg-render.js"), "utf8");

const banner = [
  "// @generated by scripts/generate-render-assets.ts",
  "// Do not edit by hand. Run `pnpm tsx scripts/generate-render-assets.ts` to refresh.",
  "",
].join("\n");

const body = [
  `export const ARG_RENDER_CSS: string = ${JSON.stringify(css)};`,
  "",
  `export const ARG_RENDER_JS: string = ${JSON.stringify(js)};`,
  "",
].join("\n");

writeFileSync(outPath, banner + body, "utf8");
process.stdout.write(
  `generate-render-assets: wrote ${outPath} (css ${css.length}B, js ${js.length}B)\n`,
);
